services:
  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
    
