services:
  auth_service:
    container_name: auth_service
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
  
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - auth_service

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:
